name: manually deploy storybook pages

on: [workflow_dispatch]

jobs:
  setup-node:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache-volta
        id: cache-volta
        uses: actions/cache@v2
        with:
          path: |
            ~/.volta
            ~/.npm
            ~/.bash_profile
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: install volta
        if: steps.cache-volta.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          touch ~/.bash_profile
          curl https://get.volta.sh | bash
          source ~/.bash_profile
      - name: install dependencies
        if: steps.cache-volta.outputs.cache-hit != 'true'
        run: |
          yarn install
  build:
    runs-on: ubuntu-20.04
    needs:
      - setup-node
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache-volta
        id: cache-volta
        uses: actions/cache@v2
        with:
          path: |
            ~/.volta
            ~/.npm
            ~/.bash_profile
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: source ~/.bash_profile
      - name: build
        run: |
          yarn run build-storybook
      - name: 'Deploy Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./storybook-static
